fix: Add PlanningPinToIndex to Python, allow it to be Integer instead of int
TimefoldAI/timefold-solver pull request #1191
Opened 2024-11-08 22:58 UTC by Christopher-Chianelli

JPyInterpreter

- Allow annotations to specify a type to override the generated getter return type. When a type is specified, it goes through the generic PythonLikeObject to Java Object convertor.

Python

- Add PlanningPinToIndex
- Make PlanningPin use the new JPyInterpreter mechanism to remove code that converts a PlanningPin to Pinning filter

Java

- Make PlanningPinToIndex support Integer, since its Javadoc says null is a valid value

Build

- Fix Python 3.12 environment name in `tox.ini`

2024-11-08 22:58 UTC, Christopher-Chianelli commented
Fixes #1190

2024-11-09 06:09 UTC, triceo requested changes
The field should not support `null` values - there is no reason for why the field should have a reference type.

If Python needs this, then it's a Python problem that needs to be solved in the Python solver - let's not make the Java model worse to support Python.

2024-11-10 06:10 UTC, triceo commented
> * `@PlanningPin` allows null/using Boolean (i.e. not allowing Integer will be inconsistent)

You could also say that we shouldn't repeat mistakes of the past. 

> * There is no performance benefit from not allowing `Integer`, since the field is automatically boxed by `MemberAccessor`

I agree. Performance is irrelevant here. I simply do not see the point of allowing this field to have a third state (`null`).

> * Users might have restrictions that prevent them from using primitive types.

This particular type has not supported `null` since the start, and there were zero complaints. That tells me `null` is not necessary there. (Besides the fact that there is no practical use for putting `null` here - zero is the perfect default for this use case.)

2024-11-11 18:40 UTC, triceo approved these changes

2024-11-11 18:42 UTC, merged