Support deep_planning_clone class decorator
TimefoldAI/timefold-solver pull request #1271
Opened 2024-12-11 04:31 UTC by luxaritas

This brings parity with the Java version (I also found that DeepPlanningClone did not work on a planning solution ProblemFactCollectionProperty, whereas marking the entire class to deep clone does)

2024-12-11 05:31 UTC, triceo commented
Thank you for your contribution, @luxaritas!

We are a bit short-handed at the moment, with many people already taking their year-end holidays. I'm going to leave this one open until my colleague, who owns the Python part of the codebase, comes back and does a code review. 

Please be patient - we have every intention to merge this PR.

2024-12-11 06:27 UTC, triceo commented
On a general note though:

- Please make sure the existing test coverage passes. At the moment, it does not:

    py310: commands[0]> pytest --import-mode=importlib python/python-core/tests
ImportError while loading conftest '/Users/runner/work/timefold-solver/timefold-solver/python/python-core/tests/conftest.py'.
python/python-core/tests/conftest.py:1: in <module>
    import timefold.solver
.tox/py310/lib/python3.10/site-packages/timefold/solver/__init__.py:50: in <module>
    import timefold.solver.domain as domain
.tox/py310/lib/python3.10/site-packages/timefold/solver/domain/__init__.py:28: in <module>
    from ._annotations import *
.tox/py310/lib/python3.10/site-packages/timefold/solver/domain/_annotations.py:876: in <module>
    def deep_planning_clone(entity_class: Type[A] = None) -> Type[A]: E   NameError: name 'A' is not defined
py310: exit 4 (0.21 seconds) /Users/runner/work/timefold-solver/timefold-solver> pytest --import-mode=importlib python/python-core/tests pid=3876

This issue also happens on Python 3.11 and 3.12. (We do not yet support 3.13.)

- Please introduce extra coverage for your change. There ought to be a test to check whether the deep-cloning works when declared.

2024-12-11 16:11 UTC, luxaritas commented
Completely understand folks being out - I have my own local adjustments for my PRs so no big deal for me anyways!

I caught the CI failure after I'd already stepped away - copy-paste error. Will look into tests as well.

2025-01-06 17:47 UTC, Christopher-Chianelli requested changes
Thanks for your contribution!
Docstring for attribute DeepPlanningClone should still mention planning_entity/planning_solution (those attributes are automatically planning cloned). Also need to test if a new instance is created in the test.
The actual implementation looks correct.

2025-01-06 17:47 UTC, Christopher-Chianelli commented on python/python-core/src/main/python/domain/_annotations.py
> -    Marks a problem fact class as being required to be deep planning cloned.
Please keep this in the docstring; attributes that are instances of a planning_entity and planning_solution type are automatically deep cloned.

2025-01-06 17:47 UTC, Christopher-Chianelli commented on python/python-core/tests/test_domain.py
> +    assert solution.codes[0].parent_entity == solution.entities[0]
There should be an assert here to test if the cloning created a new instance
```suggestion
    assert solution.codes[0].parent_entity == solution.entities[0]
    assert solution.codes[0] is not problem.codes[0]
```

2025-01-07 09:21 UTC, triceo commented
Hello @luxaritas - 2025 is here, we are back, and your PR's been reviewed.
Please resolve the comments and the one minor conflict, so that we can merge your work.

2025-01-08 23:07 UTC, luxaritas commented
Resolved and rebased!

2025-01-09 06:12 UTC, merged

2025-01-09 06:13 UTC, triceo commented
Thank you, @luxaritas! Scheduled for a next-week release.