chore: Move implementations of Collectors outside of ConstraintCollectors
TimefoldAI/timefold-solver pull request #392
Opened 2023-11-01 21:18 UTC by Christopher-Chianelli

2023-11-02 06:05 UTC, triceo requested changes
What a job, Chris! I like how you break down the collectors in smaller pieces, and I like the new hierarchy.

Unfortunately, there'll have to be some changes, see my comments. Please let me know if you want to discuss any of these - I'm available as always.

Also, I will run benchmarks on this over the weekend, just to double-check there was no negative impact.

2023-11-02 11:47 UTC, Christopher-Chianelli commented on core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintCollectors.java
>      public static <A> UniConstraintCollector<A, ?, SortedSet<A>> toSortedSet(Comparator<? super A> comparator) {
To be tested;  I am pretty sure the TreeMap would be corrupted if something like this occurs:

```
ConstraintCollectors.toSortedSet(Comparator.comparing(Entity::myPlanningVariable));
// ... sorted-set = {1, 2, 3, 4, 5, 6, 7, 8}, entity.myPlanningVariable=4
beforeVariableChange(entity, "myPlanningVariable");
entity.setMyPlanningVariable(10);
afterVariableChange(entity, "myPlanningVariable");
```
In particular, the remove call will have entity.myPlanningVariable=10

2023-11-02 11:50 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintCollectors.java
>      public static <A> UniConstraintCollector<A, ?, SortedSet<A>> toSortedSet(Comparator<? super A> comparator) {
Yes, I think so too - but it's always best to test, not guess.

2023-11-02 19:32 UTC, triceo approved these changes
A few more minor comments; if we're touching this, we may as well clean it up.

I'll merge this after I've run the benchmarks.
Nice one, @Christopher-Chianelli!

2023-11-02 19:32 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/stream/IntCounter.java
> +    public Integer result() {
Since there are no generics here, can we return `int`? Let's return what we have, and deal with boxing elsewhere.

2023-11-02 19:32 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/stream/LongCounter.java
> +    public Long result() {
`long` instead of `Long`?

2023-11-02 19:32 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/stream/ToMapPerKeyCounter.java
> +                .orElseThrow(() -> new IllegalStateException("Programming error: Should have had at least one value."));
```suggestion
                .orElseThrow(() -> new IllegalStateException("Impossible state: Should have had at least one value."));
```

"Impossible state" seems to be the convention for this.

2023-11-02 19:32 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/stream/bi/ComposeFourBiCollector.java
> +        ComposeFourBiCollector<?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?> that =
I'd argue we can avoid this craziness with `var`.
The type is already on the right-hand side of the assignment, no need to duplicate it.

Let's try to apply it consistently.

2023-11-02 19:32 UTC, triceo commented on core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/stream/bi/CountLongBiCollector.java
> +    }
If you make argless `count...()` a singleton, you get to avoid this, and also needless instances.
(Not that it'd ever be a problem.)

2023-11-03 13:22 UTC, triceo commented
So far I have confirmed that none of the CS changes had impact on performance, positive or negative.
Tonight I will benchmark this PR.

2023-11-04 07:13 UTC, merged

2023-11-04 07:14 UTC, triceo commented
Results of the benchmarks were largely positive.