chore: maintenanceScheduling diagrams
TimefoldAI/timefold-solver pull request #459
Opened 2023-12-01 13:37 UTC by ge0ffrey

2023-12-01 13:59 UTC, triceo requested changes
I believe we no longer use `readyDate` and `dueDate`. Please fix the picture.

2023-12-04 20:00 UTC, ge0ffrey commented
@triceo For now, in the maintenance scheduling quickstart, we still have ready and due.
In the long run, we will all need to standarize that to minStart and maxEnd (it's more flexible and more clear).
But until than, I guess it's good as is?

2023-12-04 20:05 UTC, triceo commented
Hmm, interesting, I swear I saw a PR changing it. I guess there's still some quickstarts where it remains. Fair enough.

2023-12-04 20:06 UTC, triceo approved these changes

2023-12-04 20:06 UTC, merged